import { getEntityPrototype } from './prototype-registry';
import { SpatialIndex, entityBottomY, occupiedCells, spatialProfileForEntity } from './spatial-index';
import type { EntityId, TransformComponent, WorldEntity, WorldState } from './types';
export interface EntityTransformPatch{readonly id:EntityId;readonly transform:TransformComponent;}
export function supportTopY(entity:WorldEntity):number|null{const surface=getEntityPrototype(entity.prototypeId).capabilities?.surface;if(!surface||surface.status!=='implemented'||!surface.acceptsFurni)return null;return normalize(entityBottomY(entity)+surface.height);}
export function supportingEntityIds(state:WorldState,candidate:WorldEntity):readonly EntityId[]{const profile=spatialProfileForEntity(candidate);if(!profile)return[];const bottomY=entityBottomY(candidate);const index=SpatialIndex.fromWorld(state),byId=new Map(state.entities.map(e=>[e.id,e])),ids=new Set<EntityId>();for(const position of occupiedCells(candidate.components.transform.position,profile.footprint))for(const occupant of index.entitiesInColumn(position)){if(occupant.entityId===candidate.id)continue;const support=byId.get(occupant.entityId);if(support&&Math.abs((supportTopY(support)??Infinity)-bottomY)<1e-6)ids.add(support.id);}return[...ids];}
export function stackGroupIds(state:WorldState,rootId:EntityId):readonly EntityId[]{if(!state.entities.some(e=>e.id===rootId))return[];const result=new Set<EntityId>([rootId]);let changed=true;while(changed){changed=false;for(const e of state.entities){if(result.has(e.id))continue;if(supportingEntityIds(state,e).some(id=>result.has(id))){result.add(e.id);changed=true;}}}return[...result];}
export function translatedStackTransforms(state:WorldState,rootId:EntityId,rootTransform:TransformComponent):readonly EntityTransformPatch[]{const root=state.entities.find(e=>e.id===rootId);if(!root)return[];const dx=rootTransform.position.x-root.components.transform.position.x,dz=rootTransform.position.z-root.components.transform.position.z,de=rootTransform.y-root.components.transform.y;return stackGroupIds(state,rootId).flatMap(id=>{const e=state.entities.find(c=>c.id===id);if(!e)return[];if(id===rootId)return[{id,transform:rootTransform}];const t=e.components.transform;return[{id,transform:{...t,position:{x:t.position.x+dx,z:t.position.z+dz},y:normalize(t.y+de)}}];});}
function normalize(v:number):number{return Math.round(v*1e6)/1e6;}
