import { ENTITY_PROTOTYPES, getEntityPrototype } from './prototype-registry';
import { parseAppearanceComponent } from './material-design';
import { FLOOR_FINISHES, WALL_FINISHES } from './room-finishes';
import { MAX_PLACEMENT_Y, MIN_PLACEMENT_Y, adjacentCellsForWall, wallKey } from './room-topology';
import type { WorldEntity, WorldState } from './types';
import { isValidEntityPlacement } from './world-placement';
export interface WorldValidationResult{readonly valid:boolean;readonly errors:readonly string[];}
export function validateWorldState(state:WorldState):WorldValidationResult{const errors:string[]=[];validateTopology(state,errors);const ids=new Set<string>(),known:WorldEntity[]=[];for(const entity of state.entities){if(ids.has(entity.id))errors.push(`Duplicate entity id: ${entity.id}.`);ids.add(entity.id);if(!ENTITY_PROTOTYPES.has(entity.prototypeId)){errors.push(`Entity ${entity.id} references unknown prototype ${entity.prototypeId}.`);continue;}known.push(entity);validateEntitySchema(entity,errors);}const knownState={...state,entities:known};for(const entity of known)if(!isValidEntityPlacement(knownState,entity))errors.push(`Entity ${entity.id} has an invalid spatial placement.`);validateRuntimeLinks(knownState,errors);return{valid:errors.length===0,errors};}
function validateTopology(state:WorldState,errors:string[]):void{const floorFinishes=new Set(FLOOR_FINISHES.map(f=>f.id)),wallFinishes=new Set(WALL_FINISHES.map(f=>f.id)),cellKeys=new Set<string>();if(!state.topology.cells.length)errors.push('Room topology needs at least one floor slab.');for(const cell of state.topology.cells){const key=`${cell.y}:${cell.position.x},${cell.position.z}`;if(cellKeys.has(key))errors.push(`Duplicate floor slab ${key}.`);cellKeys.add(key);if(!Number.isInteger(cell.position.x)||!Number.isInteger(cell.position.z))errors.push(`Floor slab ${key} must use integer X/Z.`);if(!Number.isFinite(cell.y)||cell.y<MIN_PLACEMENT_Y||cell.y>MAX_PLACEMENT_Y)errors.push(`Floor slab ${key} has invalid Y.`);if(!floorFinishes.has(cell.floorFinish))errors.push(`Floor slab ${key} has unknown finish ${cell.floorFinish}.`);}const wallKeys=new Set<string>();for(const wall of state.topology.walls){const key=wallKey(wall);if(wallKeys.has(key))errors.push(`Duplicate wall ${key}.`);wallKeys.add(key);if(!Number.isInteger(wall.x)||!Number.isInteger(wall.z)||!Number.isFinite(wall.y))errors.push(`Wall ${key} must use integer X/Z and a finite Y.`);if(wall.y<MIN_PLACEMENT_Y||wall.y>MAX_PLACEMENT_Y)errors.push(`Wall ${key} is outside the supported Y range.`);if(!wallFinishes.has(wall.finish))errors.push(`Wall ${key} has unknown finish ${wall.finish}.`);if(!adjacentCellsForWall(state.topology,wall).length)errors.push(`Wall ${key} touches no floor slab.`);}}
function validateEntitySchema(entity:WorldEntity,errors:string[]):void{const t=entity.components.transform;if(!Number.isInteger(t.position.x)||!Number.isInteger(t.position.z))errors.push(`Entity ${entity.id} has a non-integer grid transform.`);if(![0,1,2,3].includes(t.rotation))errors.push(`Entity ${entity.id} has an invalid quarter rotation.`);if(!Number.isFinite(t.y)||t.y<MIN_PLACEMENT_Y||t.y>MAX_PLACEMENT_Y)errors.push(`Entity ${entity.id} has an invalid bottom Y.`);const prototype=getEntityPrototype(entity.prototypeId),toggle=entity.components.toggle,toggleCapability=prototype.capabilities?.toggle;if(toggle&&(!toggleCapability||toggleCapability.status!=='implemented'))errors.push(`Entity ${entity.id} has toggle state without an implemented toggle capability.`);else if(toggle&&(toggle.state<0||toggle.state>=toggleCapability!.states))errors.push(`Entity ${entity.id} has toggle state outside its prototype range.`);if(entity.components.teleporter&&prototype.capabilities?.teleport?.status!=='implemented')errors.push(`Entity ${entity.id} has teleporter state without an implemented teleport capability.`);if(entity.components.appearance){const appearance=parseAppearanceComponent(entity.components.appearance);if(!appearance)errors.push(`Entity ${entity.id} has an invalid material appearance.`);else{const allowed=new Set(prototype.renderable.materialSlots?.map(s=>s.id)??[]);for(const slotId of Object.keys(appearance.materials))if(!allowed.has(slotId))errors.push(`Entity ${entity.id} customizes unknown material slot ${slotId}.`);}}}
function validateRuntimeLinks(state:WorldState,errors:string[]):void{const ids=new Set(state.entities.map(e=>e.id));for(const entity of state.entities){const prototype=getEntityPrototype(entity.prototypeId),targetId=entity.components.teleporter?.targetEntityId;if(targetId&&!ids.has(targetId))errors.push(`Teleporter ${entity.id} references missing target entity ${targetId}.`);if(targetId&&prototype.capabilities?.teleport?.paired){const target=state.entities.find(c=>c.id===targetId);if(!target||target.components.teleporter?.targetEntityId!==entity.id)errors.push(`Paired teleporter ${entity.id} does not have a reciprocal link.`);}const actor=entity.components.actor;if(!actor?.seatedOn)continue;const seatEntity=state.entities.find(c=>c.id===actor.seatedOn),sit=seatEntity?getEntityPrototype(seatEntity.prototypeId).capabilities?.sit:undefined;if(!seatEntity||!sit||sit.status!=='implemented'||actor.seatIndex===undefined||!sit.seats[actor.seatIndex])errors.push(`Actor ${entity.id} references an invalid seat attachment.`);}}
