import { css } from 'lit';

export const materialStudioStyles = css`
  :host{display:block;width:min(640px,calc(100vw - 24px));color:#33484d}
  hotel-panel{display:block}.studio{display:grid;grid-template-columns:190px minmax(0,1fr);gap:12px;min-height:410px}
  .preview-column{display:flex;flex-direction:column;gap:8px}.preview{height:178px;border:2px solid #96a6a3;border-radius:6px;background:linear-gradient(#eaf3f4,#cddfe0);overflow:hidden;box-shadow:inset 0 2px rgba(255,255,255,.8)}
  catalogue-object-preview{width:100%;height:100%}.object-title{font-size:11px;font-weight:950}.object-subtitle{margin-top:2px;color:#718085;font-size:8px;line-height:1.35}
  .slots{display:grid;gap:4px}.slot{display:grid;grid-template-columns:1fr auto;gap:6px;align-items:center;min-height:38px;padding:5px 7px;border:2px solid #9aa7a4;border-radius:5px;background:#f6f8f7;color:#40555a;text-align:left;font:inherit;cursor:pointer;box-shadow:inset 0 2px rgba(255,255,255,.8)}
  .slot.active{border-color:#4e7d8e;background:#e0eef1;box-shadow:0 0 0 2px #bed9df}.slot strong{display:block;font-size:9px}.slot small{display:block;margin-top:1px;color:#7b888b;font-size:7px}.override{padding:2px 4px;border-radius:999px;background:#5d8a70;color:white;font-size:6px;font-weight:950;text-transform:uppercase}
  .editor{min-width:0;overflow:auto;padding-right:2px}.section{margin-bottom:10px}.section-head{display:flex;align-items:end;justify-content:space-between;gap:8px;margin-bottom:5px}.section-title{font-size:9px;font-weight:950;text-transform:uppercase;letter-spacing:.05em;color:#51686d}.section-note{font-size:7px;color:#7d898c;text-align:right}
  .preset-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}.preset{min-height:44px;padding:6px 7px;border:2px solid #97a5a2;border-radius:5px;background:#f7f9f8;color:#385056;text-align:left;font:inherit;cursor:pointer}.preset strong{display:block;font-size:9px}.preset span{display:block;margin-top:2px;color:#798689;font-size:7px;line-height:1.25}.preset.active{border-color:#598493;background:#e2eff2}
  .fields{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.field{display:grid;gap:3px;color:#64767a;font-size:7px;font-weight:900}.field input,.field select{width:100%;height:34px;box-sizing:border-box;border:2px solid #97a4a2;border-radius:4px;background:#fff;color:#34494f;font:inherit;font-size:9px;padding:4px 6px}.field input[type=color]{padding:2px}.field.wide{grid-column:span 2}
  .layers{display:flex;gap:4px;overflow-x:auto;padding:1px 1px 4px}.layer{flex:0 0 auto;min-height:32px;padding:4px 7px;border:2px solid #9aa7a4;border-radius:5px;background:#f5f7f6;color:#485c61;font:900 8px inherit;cursor:pointer}.layer.active{border-color:#537e8e;background:#e2eef1}.add-layer{display:flex;gap:5px}.add-layer select{flex:1;min-width:0;height:34px;border:2px solid #97a4a2;border-radius:4px;background:#fff;font:inherit;font-size:9px;color:#34494f}.small-action{min-height:34px;border:2px solid #647b71;border-radius:5px;background:#779082;color:white;font:900 8px inherit;padding:0 8px;cursor:pointer}.small-action.danger{border-color:#6b494b;background:#986164}.small-action.ghost{color:#52676b;background:#edf1f0;border-color:#9ba8a5}
  .layer-editor{margin-top:5px;padding:7px;border:1px solid #aab5b2;border-radius:5px;background:#edf2f0}.layer-actions{display:flex;justify-content:flex-end;margin-top:6px}
  .saved-row{display:flex;gap:5px;align-items:center}.saved-row input{flex:1;min-width:0;height:34px;box-sizing:border-box;border:2px solid #97a4a2;border-radius:4px;padding:4px 7px;font:inherit;font-size:9px}.saved-list{display:flex;gap:4px;overflow-x:auto;margin-top:5px;padding-bottom:3px}.saved{display:flex;align-items:center;flex:0 0 auto;border:2px solid #9ba8a5;border-radius:5px;overflow:hidden;background:#f7f9f8}.saved button{min-height:34px;border:0;background:transparent;color:#40555a;font:900 8px inherit;padding:0 8px;cursor:pointer}.saved .delete{padding:0 7px;color:#8a4d51;border-left:1px solid #bdc6c3}
  .advanced{margin-top:7px;border:1px solid #aab4b2;border-radius:5px;background:#eef2f1}.advanced summary{padding:6px 7px;font-size:8px;font-weight:950;cursor:pointer;color:#627276}.advanced-body{padding:0 7px 7px}.recipe{max-height:82px;overflow:auto;margin:5px 0 0;padding:6px;border-radius:4px;background:#26383d;color:#d7ecee;font:7px/1.35 ui-monospace,SFMono-Regular,monospace;white-space:pre-wrap;word-break:break-word}
  .footer{display:flex;justify-content:space-between;gap:8px;margin-top:10px;padding-top:8px;border-top:2px solid #bdc7c4}.footer-group{display:flex;gap:5px}.action{min-height:38px;padding:0 11px;border:2px solid #52685d;border-radius:5px;background:#6f8b78;color:white;font:900 9px inherit;cursor:pointer;box-shadow:inset 0 2px rgba(255,255,255,.18)}.action.primary{border-color:#355f4a;background:#5e906c}.action.secondary{color:#4a5f64;border-color:#98a5a2;background:#f0f3f2}.action.danger{border-color:#6e4447;background:#985c60}.message{margin-top:6px;padding:6px 7px;border-radius:4px;background:#7d4249;color:white;font-size:8px;font-weight:850}
  @media(max-width:680px){:host{width:100vw;max-width:none}.studio{grid-template-columns:1fr;gap:8px;height:min(68dvh,590px);overflow:auto;overscroll-behavior:contain;padding-right:1px}.preview-column{display:grid;grid-template-columns:112px minmax(0,1fr);align-items:start}.preview{height:112px}.object-copy{padding-top:2px}.slots{grid-column:1/-1;display:flex;overflow-x:auto}.slot{flex:0 0 132px;min-height:44px}.editor{overflow:visible}.preset{min-height:48px}.field input,.field select,.saved-row input,.add-layer select{height:44px;font-size:16px}.small-action,.layer,.saved button{min-height:44px}.action{min-height:44px}.footer{position:sticky;bottom:0;z-index:4;margin:8px -1px -1px;padding:8px 1px max(2px,env(safe-area-inset-bottom));background:#e7ece9}.footer .action{flex:1}.footer-group{flex:1}.section-note{font-size:8px}}
  @media(max-width:410px){.fields{grid-template-columns:repeat(2,minmax(0,1fr))}.preset-grid{grid-template-columns:1fr}.footer{flex-direction:column}.footer-group{width:100%}}
`;
