import { css } from 'lit';

export const materialStudioStyles = css`
  :host{display:block;position:absolute;inset:0;color:#33484d}
  .backdrop{width:100%;height:100%;box-sizing:border-box;display:grid;place-items:stretch;padding:18px;background:rgba(8,18,25,.62)}
  hotel-panel{display:block;width:100%;height:100%;min-height:0}
  hotel-panel::part(body){min-height:0}
  .studio{display:grid;grid-template-columns:minmax(240px,34%) minmax(0,1fr);gap:16px;height:calc(100dvh - 122px);min-height:0}
  .preview-column{min-width:0;overflow:auto;padding-right:2px}.preview-column material-swatch-preview{width:min(100%,430px);margin:0 auto}.preview-copy{width:min(100%,430px);margin:9px auto 0}.preview-copy strong{display:block;color:#38535a;font-size:11px}.preview-copy span,.subtle{display:block;margin-top:3px;color:#718085;font-size:8px;line-height:1.4}
  .library{width:min(100%,430px);margin:14px auto 0}.editor{min-width:0;overflow:auto;overscroll-behavior:contain;padding-right:3px}.section{margin-bottom:14px}.section-head{display:flex;align-items:end;justify-content:space-between;gap:8px;margin-bottom:6px}.section-title{font-size:9px;font-weight:950;text-transform:uppercase;letter-spacing:.05em;color:#51686d}.section-note{font-size:7px;color:#7d898c;text-align:right}
  .preset-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.preset{min-height:54px;padding:7px 8px;border:2px solid #97a5a2;border-radius:5px;background:#f7f9f8;color:#385056;text-align:left;font:inherit;cursor:pointer;box-shadow:inset 0 2px rgba(255,255,255,.74),0 2px #c1cac7}.preset strong{display:block;font-size:9px}.preset span{display:block;margin-top:3px;color:#798689;font-size:7px;line-height:1.25}.preset:hover{border-color:#65838a;background:#fff}.preset.active{border-color:#598493;background:#e2eff2;box-shadow:0 0 0 2px #bed8df}
  .fields{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.field{display:grid;gap:3px;color:#64767a;font-size:7px;font-weight:900}.field input,.field select{width:100%;height:36px;box-sizing:border-box;border:2px solid #97a4a2;border-radius:4px;background:#fff;color:#34494f;font:inherit;font-size:9px;padding:4px 6px}.field input[type=color]{padding:2px}
  .layers{display:flex;gap:4px;overflow-x:auto;padding:1px 1px 5px}.layer{flex:0 0 auto;min-height:34px;padding:4px 8px;border:2px solid #9aa7a4;border-radius:5px;background:#f5f7f6;color:#485c61;font:900 8px inherit;cursor:pointer}.layer.active{border-color:#537e8e;background:#e2eef1}.add-layer{display:flex;gap:5px}.add-layer select{flex:1;min-width:0;height:36px;border:2px solid #97a4a2;border-radius:4px;background:#fff;font:inherit;font-size:9px;color:#34494f}.small-action{min-height:36px;border:2px solid #647b71;border-radius:5px;background:#779082;color:white;font:900 8px inherit;padding:0 9px;cursor:pointer}.small-action.danger{border-color:#6b494b;background:#986164}.small-action.ghost{color:#52676b;background:#edf1f0;border-color:#9ba8a5}.close-studio{width:32px;padding:0;font-size:12px}
  .layer-editor{margin-top:6px;padding:8px;border:1px solid #aab5b2;border-radius:5px;background:#edf2f0}.layer-actions{display:flex;justify-content:flex-end;margin-top:7px}
  .saved-row{display:flex;gap:5px;align-items:center}.saved-row input{flex:1;min-width:0;height:36px;box-sizing:border-box;border:2px solid #97a4a2;border-radius:4px;padding:4px 7px;font:inherit;font-size:9px}.saved-list{display:flex;gap:4px;flex-wrap:wrap;margin-top:6px}.saved{display:flex;align-items:center;border:2px solid #9ba8a5;border-radius:5px;overflow:hidden;background:#f7f9f8}.saved button{min-height:34px;border:0;background:transparent;color:#40555a;font:900 8px inherit;padding:0 8px;cursor:pointer}.saved .delete{padding:0 7px;color:#8a4d51;border-left:1px solid #bdc6c3}
  .advanced{margin-top:8px;border:1px solid #aab4b2;border-radius:5px;background:#eef2f1}.advanced summary{padding:7px 8px;font-size:8px;font-weight:950;cursor:pointer;color:#627276}.advanced-body{padding:0 8px 8px}.recipe{max-height:160px;overflow:auto;margin:6px 0 0;padding:7px;border-radius:4px;background:#26383d;color:#d7ecee;font:7px/1.4 ui-monospace,SFMono-Regular,monospace;white-space:pre-wrap;word-break:break-word}.message{margin-top:7px;padding:7px 8px;border-radius:4px;background:#7d4249;color:white;font-size:8px;font-weight:850}
  .footer{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:10px;padding-top:8px;border-top:2px solid #bdc7c4}.footer-note{color:#718085;font-size:8px}.action{min-height:38px;padding:0 16px;border:2px solid #52685d;border-radius:5px;background:#6f8b78;color:white;font:900 9px inherit;cursor:pointer;box-shadow:inset 0 2px rgba(255,255,255,.18)}.action.primary{border-color:#355f4a;background:#5e906c}
  @media(max-width:900px){.preset-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.fields{grid-template-columns:repeat(2,minmax(0,1fr))}}
  @media(max-width:680px){.backdrop{padding:0}.studio{grid-template-columns:1fr;height:calc(100dvh - 126px);overflow:auto;padding-right:1px}.preview-column{overflow:visible}.preview-column material-swatch-preview{width:min(72vw,280px)}.preview-copy{width:min(72vw,280px)}.library{width:100%}.editor{overflow:visible}.preset{min-height:48px}.field input,.field select,.saved-row input,.add-layer select{height:44px;font-size:16px}.small-action,.layer,.saved button{min-height:44px}.close-studio{width:44px}.action{min-height:44px}.footer{position:sticky;bottom:0;z-index:4;margin:8px -1px -1px;padding:8px 1px max(2px,env(safe-area-inset-bottom));background:#e7ece9}.footer-note{display:none}.footer .action{width:100%}}
  @media(max-width:410px){.preset-grid{grid-template-columns:1fr}}
`;
