import type { InteractionAccessContext } from '../domain/interaction-types';
import { canTraverseTopologyEdge, roomCellAt } from '../domain/room-topology';
import { SpatialIndex, addressKey } from '../domain/spatial-index';
import { traversalNeighbors } from '../domain/traversal-links';
import type { CellAddress, EntityId, GridPoint, WorldState } from '../domain/types';
import { canTraverseBetween, canTraverseCell } from './traversal-system';
const NEIGHBORS=[{x:0,z:-1},{x:1,z:-1},{x:1,z:0},{x:1,z:1},{x:0,z:1},{x:-1,z:1},{x:-1,z:0},{x:-1,z:-1}] as const;
export function directionForStep(from:GridPoint,to:GridPoint):number{const dx=Math.sign(to.x-from.x),dz=Math.sign(to.z-from.z);if(dx===0&&dz<0)return 0;if(dx>0&&dz<0)return 1;if(dx>0&&dz===0)return 2;if(dx>0&&dz>0)return 3;if(dx===0&&dz>0)return 4;if(dx<0&&dz>0)return 5;if(dx<0&&dz===0)return 6;return 7;}
export function findActorPath(state:WorldState,actorId:EntityId,start:CellAddress,target:CellAddress,allowBlockedTarget=false,access?:InteractionAccessContext):readonly CellAddress[]|null{
  const index=SpatialIndex.fromWorld(state);if(!roomCellAt(state.topology,target))return null;const context={actorId,state,index,...(access?{access}:{})};if(!allowBlockedTarget&&!canTraverseCell(context,target))return null;if(same(start,target))return[];
  const open=new Set<string>([addressKey(start)]),came=new Map<string,CellAddress>(),g=new Map<string,number>([[addressKey(start),0]]),cells=new Map<string,CellAddress>([[addressKey(start),start]]);
  while(open.size){const currentKey=lowest(open,g,cells,target),current=cells.get(currentKey)!;if(same(current,target))return reconstruct(came,current,start);open.delete(currentKey);for(const next of neighborsFor(state,current)){const isTarget=same(next,target);if(isTarget&&allowBlockedTarget){if(!canTraverseTopologyEdge(state.topology,current,next)&&!traversalNeighbors(state,current).some(c=>same(c,next)))continue;}else if(!canTraverseBetween(context,current,next))continue;if(isDiagonal(current,next)&&!canCutCorner(current,next,context,target,allowBlockedTarget))continue;const key=addressKey(next),cost=(g.get(currentKey)??Infinity)+movementCost(current,next);if(cost>=(g.get(key)??Infinity))continue;came.set(key,current);g.set(key,cost);cells.set(key,next);open.add(key);}}
  return null;
}
function neighborsFor(state:WorldState,current:CellAddress):readonly CellAddress[]{const planar=NEIGHBORS.flatMap(delta=>state.topology.cells.filter(c=>c.position.x===current.position.x+delta.x&&c.position.z===current.position.z+delta.z&&Math.abs(c.y-current.y)<=1).map(c=>({position:c.position,y:c.y})));const unique=new Map<string,CellAddress>();for(const a of[...planar,...traversalNeighbors(state,current)])unique.set(addressKey(a),a);return[...unique.values()];}
function canCutCorner(current:CellAddress,next:CellAddress,context:Parameters<typeof canTraverseBetween>[0],target:CellAddress,allowBlockedTarget:boolean):boolean{const dx=Math.sign(next.position.x-current.position.x),dz=Math.sign(next.position.z-current.position.z);const sides=[{position:{x:current.position.x+dx,z:current.position.z},y:current.y},{position:{x:current.position.x,z:current.position.z+dz},y:current.y}];return sides.every(side=>(allowBlockedTarget&&same(side,target))||canTraverseBetween(context,current,side));}
function reconstruct(came:ReadonlyMap<string,CellAddress>,end:CellAddress,start:CellAddress):CellAddress[]{const result:CellAddress[]=[];let current=end;while(!same(current,start)){result.push(current);const previous=came.get(addressKey(current));if(!previous)return[];current=previous;}return result.reverse();}
function lowest(open:ReadonlySet<string>,g:ReadonlyMap<string,number>,cells:ReadonlyMap<string,CellAddress>,target:CellAddress):string{let best='',score=Infinity;for(const key of open){const a=cells.get(key)!,planar=Math.max(Math.abs(target.position.x-a.position.x),Math.abs(target.position.z-a.position.z)),next=(g.get(key)??Infinity)+planar+Math.abs(target.y-a.y)*.25;if(next<score){score=next;best=key;}}return best;}
function movementCost(a:CellAddress,b:CellAddress):number{return(a.position.x!==b.position.x&&a.position.z!==b.position.z?Math.SQRT2:1)+Math.abs(a.y-b.y)*.08;}
function isDiagonal(a:CellAddress,b:CellAddress):boolean{return a.position.x!==b.position.x&&a.position.z!==b.position.z;}
function same(a:CellAddress,b:CellAddress):boolean{return a.y===b.y&&a.position.x===b.position.x&&a.position.z===b.position.z;}
